### ISSUE TITLE
[Support]: Recording breaks if disabled by MQTT on Frigate start

### ISSUE THREAD

**Issue by rossoneri8** [blakeblackshear/frigate#2129]
### Describe the problem you are having

I have two cameras setup (same model) and both are setup via HA to enable/disable the camera's RTSP server and Frigate's Recording feature via a single button click. The problem I am experiencing is that after I enable/disable the recording feature in Frigate, the recording never resumes. When I navigate to the camera recording page I get the following error:
> No Recordings Found
> 
> Make sure you have enabled the record role in your configuration for the livingRoom camera.

And if I look at the recording folder I see no new video files are being created. I can recover the recording feature by restarting the Frigate container, but enabling/disabling the recording feature breaks it again. Looking through the logs I don't see any obvious failures, it looks like Frigate is not correctly re-enabling the recording feature.

### Version

0.9.4-26ae608

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "babyRoom": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": false,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "width": 1920
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://<user>:<pass>@<ip>:8554/unicast",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -avoid_negative_ts make_zero -i rtsp://<user>:<pass>@<ip>:8554/unicast -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/babyRoom-%Y%m%d%H%M%S.mp4 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 99,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "babyRoom",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 1
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "livingRoom": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": false,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "width": 1920
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://<user>:<pass>@<ip>:8554/unicast",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -avoid_negative_ts make_zero -i rtsp://<user>:<pass>@<ip>:8554/unicast -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/livingRoom-%Y%m%d%H%M%S.mp4 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 99,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "livingRoom",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 1
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "width": 1280
  },
  "detectors": {
    "cpu": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "+genpts+discardcorrupt",
      "-vsync",
      "drop",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "mqtt",
    "password": "<password>",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "<user>"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[2021-10-27 09:55:08] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59438]


[2021-10-27 09:55:11] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59438]


[2021-10-27 09:55:11] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59452]


[2021-10-27 09:56:39] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59452]


[2021-10-27 10:02:35] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51250]


[2021-10-27 10:02:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51250]


[2021-10-27 10:02:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59664]


[2021-10-27 10:02:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51262]


[2021-10-27 10:02:52] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51262]


[2021-10-27 10:02:56] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59664]


[2021-10-27 10:02:57] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59694]


[2021-10-27 10:02:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59694]


[2021-10-27 10:02:59] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59708]


[2021-10-27 10:03:00] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59708]


[2021-10-27 10:03:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59718]


[2021-10-27 10:03:02] frigate.mqtt                   INFO    : Turning on detection for livingRoom via mqtt


[2021-10-27 10:03:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59718]


[2021-10-27 10:03:03] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59730]


[2021-10-27 10:03:05] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59730]


[2021-10-27 10:03:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59740]


[2021-10-27 10:03:16] frigate.mqtt                   INFO    : Turning on snapshots for livingRoom via mqtt


[2021-10-27 10:03:17] frigate.mqtt                   INFO    : Turning off snapshots for livingRoom via mqtt


[2021-10-27 10:03:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59740]


[2021-10-27 10:03:22] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59770]


[2021-10-27 10:03:24] frigate.mqtt                   INFO    : Turning off detection for livingRoom via mqtt


[2021-10-27 10:03:25] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59770]


[2021-10-27 10:03:26] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59788]


[2021-10-27 10:03:27] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59788]


[2021-10-27 10:03:27] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59798]


[2021-10-27 10:03:31] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59798]


[2021-10-27 10:03:31] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59810]


[2021-10-27 10:03:33] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59810]


[2021-10-27 10:03:33] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59824]


[2021-10-27 10:03:35] frigate.mqtt                   INFO    : Turning off recordings for livingRoom via mqtt


[2021-10-27 10:03:37] frigate.mqtt                   INFO    : Turning on recordings for livingRoom via mqtt


[2021-10-27 10:03:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59824]


[2021-10-27 10:03:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59838]


[2021-10-27 10:03:42] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59838]


[2021-10-27 10:03:42] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59848]


[2021-10-27 10:03:43] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59848]


[2021-10-27 10:03:43] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59858]


[2021-10-27 10:03:44] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59858]


[2021-10-27 10:03:44] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59866]


[2021-10-27 10:03:45] frigate.mqtt                   INFO    : Turning off recordings for livingRoom via mqtt


[2021-10-27 10:03:46] frigate.mqtt                   INFO    : Turning on detection for livingRoom via mqtt


[2021-10-27 10:03:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51480]


[2021-10-27 10:03:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51480]


[2021-10-27 10:04:17] frigate.mqtt                   INFO    : Turning on recordings for livingRoom via mqtt


[2021-10-27 10:04:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51620]


[2021-10-27 10:04:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51620]


[2021-10-27 10:04:57] frigate.mqtt                   INFO    : Turning off detection for livingRoom via mqtt


[2021-10-27 10:06:39] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59866]


[2021-10-27 10:08:09] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60374]


[2021-10-27 10:09:39] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60374]
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.1-with-options Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.11)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-demuxer=dash --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-htmlpages --extra-version=with-options --enable-opencl --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x7fef29811000] max delay reached. need to consume packet
[rtsp @ 0x7fef29811000] RTP: missed 2 packets
[rtsp @ 0x7fef29811000] max delay reached. need to consume packet
[rtsp @ 0x7fef29811000] RTP: missed 7 packets
Input #0, rtsp, from 'rtsp://<user>:<pass>@<ip>:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 0.000375, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 15.08 tbr, 90k tbn, 50 tbc
  Stream #0:1: Audio: pcm_mulaw, 16000 Hz, 1 channels, s16, 128 kb/s
```

### Frigate stats

```json
{"babyRoom":{"camera_fps":5.1,"capture_pid":230,"detection_fps":0.0,"pid":227,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":215.87,"pid":219}},"livingRoom":{"camera_fps":5.1,"capture_pid":228,"detection_fps":0.0,"pid":225,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":60.2,"mount_type":"tmpfs","total":67.1,"used":6.9},"/media/frigate/clips":{"free":160025.7,"mount_type":"zfs","total":173435.4,"used":13409.7},"/media/frigate/recordings":{"free":160025.7,"mount_type":"zfs","total":173435.4,"used":13409.7},"/tmp/cache":{"free":999.5,"mount_type":"tmpfs","total":1000.0,"used":0.5}},"uptime":127266,"version":"0.9.4-26ae608"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Wyze Pan w/ dafang hacks

**Comment by guillpocovi** [comment]
I have the same issue. With previous version 0.8.x I could enable/disable clips & recordings based on whether I am at home or away. Now, I need to restart the frigate container in order for the recordings to start.

**Comment by rossoneri8** [comment]
@blakeblackshear I did a little more experimentation and I think I found the root cause. If I have the cameras set to record when frigate starts I am able to enable/disable recording without issue. However, if the MQTT state is set to disable recording when frigate starts, re-enabling at a later time does not restart recording.

**Comment by blakeblackshear** [comment]
Thanks. I think I know why that happens.

**Comment by euro2** [comment]
> 
> 
> @blakeblackshear I did a little more experimentation and I think I found the root cause. If I have the cameras set to record when frigate starts I am able to enable/disable recording without issue. However, if the MQTT state is set to disable recording when frigate starts, re-enabling at a later time does not restart recording.

Got the same issue. I hope Blake figures this out!

**Comment by rainman369** [comment]
> > @blakeblackshear I did a little more experimentation and I think I found the root cause. If I have the cameras set to record when frigate starts I am able to enable/disable recording without issue. However, if the MQTT state is set to disable recording when frigate starts, re-enabling at a later time does not restart recording.
> 
> Got the same issue. I hope Blake figures this out!

I am now having this same issue (@blakeblackshear actually brought it to my attention on another forum). Can anyone advise how I can toggle the recording on when I start frigate? I have tried toggling the recording on in frigate and home assistant, but then when I restart my frigate docker, the recording is disabled again. Looking in the log, I see where it says MQTT loads the recording as "Turning off recordings for livingroom via mqtt" but I don't know how to remedy this...

**Comment by erbryan94** [comment]
I have a similar issue - none of the suggested work-arounds have seemed to work for me either (restarting frigate/mqtt in any order and or full reboot).

it seems like I have the opposite problem right now though, in that my detection/recording/snapshot controls are all stuck on.  So I can’t toggle off any of them right now (in frigate UI, nor in HA UI through the integration).  No apparent issues in logs.

anyone else get this issue?

I had this working at one point last night, and then earlier today it seemed to be the issue others were describing (I could turn recording back on/off, but it wouldn’t actually record anything).  Unfortunately have been having some other weird issues, and have been restarting my server a lot, so hard to pin point what I did to get here.

**Comment by blakeblackshear** [comment]
What happens when you try and toggle it off in the frigate UI?

**Comment by erbryan94** [comment]
Basically just won't toggle off:

![image](https://user-images.githubusercontent.com/52016013/146311374-e84899bf-f5b0-46f4-a4e5-83aa539d221b.png)

now it seems like my HA components are unavailable as well:

![image](https://user-images.githubusercontent.com/52016013/146311599-d2a3714c-ccb0-49d7-9f95-96206717cf32.png)

**Comment by blakeblackshear** [comment]
That looks like frigate is unable to connect to mqtt.

**Comment by erbryan94** [comment]
yes, it was an mqtt issue.  was missing mqtt setup in configuration - not sure how it was working before without that lol.

Thanks!

**Comment by maxi1134** [comment]
Same issue here,
all my cameras options ( detection, recording, snapshot ) go to off for no reason.
I do not send the MQTT packet "off" manually at all, this happens on its own!

I need to explode the stored mqtt data and restart frigate for it to restart recording/detecting

Would be glad to test if you need to.

**Comment by blakeblackshear** [comment]
This is already addressed in the 0.10.0 beta version for those wanting to test.

**Comment by maxi1134** [comment]
> This is already addressed in the 0.10.0 beta version for those wanting to test.

Which beta exactly? If I can ask!

I am running "blakeblackshear/frigate:0.10.0-beta4-amd64nvidia" and the problem persists!

Would updating to beta6 fix this?

**Comment by blakeblackshear** [comment]
It should have been fixed in beta4. You may have a different issue. If you turn on the switches and then restart frigate it should remember that they were on. If not, you should ensure that frigate is using a username and password to talk to mqtt because it may not have permissions write retained values.

**Comment by rossoneri8** [comment]
@blakeblackshear I finally got a chance to check out the beta (specifically beta 6) and can confirm this bug is fixed. Thanks! Awesome job on this and frigate as a whole! WIll close out the bug.

**Comment by bogdanr** [comment]
I have the image from 7 days ago (920cbfe74eca) and after shutting down and starting frigate it always starts with detection off, even though just before shutdown detection was ON. I with there was some way to overwrite MQTT and somehow tell it to always enable detection.

**Comment by blakeblackshear** [comment]
@bogdanr have you cleared out the old retained `set` topics from MQTT?

**Comment by bogdanr** [comment]
How do I do that? I have the standard Mosquitto installation.

**Comment by blakeblackshear** [comment]
https://community.home-assistant.io/t/how-to-purge-the-retained-mqtt-messages/268083/4

**Comment by heapxor** [comment]
whats the fix for that issue? thx

**Comment by blakeblackshear** [comment]
If you have a retained message, it is going to keep turning it off on startup. The latest version at least makes it possible to turn recordings back on and have them work. You need to clear the existing retained message.

**Comment by heapxor** [comment]
@blakeblackshear hi, how can i see if i have retained message/messages? By clearing them - what do you mean? By latest version that can tackle it you mean? thanks!

**Comment by blakeblackshear** [comment]
This message means that you have a retained message that is turning on detection assuming the logs you posted are from startup:
> Turning on detection for entrance_cam via mqtt

There are instructions on clearing retained messages here: https://github.com/blakeblackshear/frigate/issues/2129#issuecomment-1052909420

**Comment by heapxor** [comment]
what exactly does it mean > retained message that is turning on detection? i mean even it shows detection is on its not on bc its retained/stuck in the queue? thanks

**Comment by heapxor** [comment]
@blakeblackshear whats the topic name? its not in the config...


      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },

**Comment by heapxor** [comment]
@blakeblackshear it doesnt work;

i tried:
1)
![image](https://user-images.githubusercontent.com/64676/159808039-de7baff3-2f7a-4d6c-85f4-ffd622c6a4d1.png)

2)
![image](https://user-images.githubusercontent.com/64676/159808090-a2df94cd-375e-4683-a4c2-1eb47fba1d30.png)


3)
![image](https://user-images.githubusercontent.com/64676/159808152-e12546c3-414f-4fa7-846b-7f5198250daa.png)


its not producing any mp4 same error ...

**Comment by NickM-27** [comment]
@heapxor That isn't the correct topic, to set recordings this topic needs to be used: https://docs.frigate.video/integrations/mqtt#frigatecamera_namerecordingsset

**Comment by heapxor** [comment]
@NickM-27 
okay, i connected to the mqtt
![image](https://user-images.githubusercontent.com/64676/159809207-b16cfecd-868b-409b-ba26-390cbeec38b7.png)
then i executed
![image](https://user-images.githubusercontent.com/64676/159809290-269c8eda-947b-44ab-abc1-97889fb936a7.png)



![image](https://user-images.githubusercontent.com/64676/159809262-82fecef3-8774-4581-b77a-865ab1e96fc7.png)


then i did movement in front of the camera ... 
![image](https://user-images.githubusercontent.com/64676/159809436-a529ba47-f384-486c-be5c-155e28a3ac26.png)


and same results.... what kind of bug is that?

**Comment by NickM-27** [comment]
> @NickM-27 okay, i connected to the mqtt ![image](https://user-images.githubusercontent.com/64676/159809207-b16cfecd-868b-409b-ba26-390cbeec38b7.png) then i executed ![image](https://user-images.githubusercontent.com/64676/159809290-269c8eda-947b-44ab-abc1-97889fb936a7.png)
> 
> ![image](https://user-images.githubusercontent.com/64676/159809262-82fecef3-8774-4581-b77a-865ab1e96fc7.png)
> 
> then i did movement in front of the camera ... ![image](https://user-images.githubusercontent.com/64676/159809436-a529ba47-f384-486c-be5c-155e28a3ac26.png)
> 
> and same results.... what kind of bug is that?

Still not quite correct. As the docs state, the topic expects a value of ON or OFF. You can verify if recordings are enabled or not under the `recordings` part.

**Comment by heapxor** [comment]
@NickM-27 i do not understand .... 
as that section is BROKEN>
![image](https://user-images.githubusercontent.com/64676/159810153-b6121eae-080d-4a5b-9b84-c98840dcfeef.png)

**Comment by NickM-27** [comment]
@heapxor 
<img width="621" alt="Screen Shot 2022-03-23 at 5 00 55 PM" src="https://user-images.githubusercontent.com/14866235/159810442-3a31fa92-2cea-4226-83b8-8ac8c6ab6c5e.png">

**Comment by heapxor** [comment]
ITS enabled .... 
![image](https://user-images.githubusercontent.com/64676/159810508-8c4f4e69-999b-4bb3-8a7d-324e2a79c97d.png)

it just doesnt record anything .... THATS Why  I raised that ISSUE /BUG

**Comment by NickM-27** [comment]
@heapxor Then I would recommend creating a new issue following the issue template. This issue (about MQTT set / retain) is unrelated to what you are experiencing

**Comment by heapxor** [comment]
i dont get it ... so what do i have to report?

**Comment by heapxor** [comment]
this is so annoying.

**Comment by NickM-27** [comment]
> i dont get it ... so what do i have to report?

The issue template will walk you through it. But we need to see your config as it is currently and what exactly is going on. It's too difficult to see / follow your case at the bottom of this issue which at this point is unrelated to what is causing your recordings to not be working.

**Comment by heapxor** [comment]
its here>https://github.com/blakeblackshear/frigate/issues/3008
