### ISSUE TITLE
UDP rtsp stream weird behavior

### ISSUE THREAD

**Issue by koncode** [blakeblackshear/frigate#22]
My cameras don't support rtsp over tcp, they use udp instead. I managed to successfully start the container was using the environment variable :
`-e OPENCV_FFMPEG_CAPTURE_OPTIONS="rtsp_transport;udp"` and i can see the feed on my browser. 

The problem is that it seems to give high confidence false positives. I am attaching a screenshot to help you better understand the problem. My guess is that the video feed is parsed incorrectly. Do you have any clue as to how i can debug it or solve it? 

I tried streaming rtsp over udp using my phone camera and an app and i have the same behavior. I am running the blakeblackshear/frigate:edgetpu image and i have tried building the container from the Dockerfile one the repository as well and i always get the same issue.

Thank you in advance.
![Capture](https://user-images.githubusercontent.com/10908240/55982134-ea7b9080-5ca0-11e9-888c-3d39a83c951b.PNG)

**Comment by koncode** [comment]
I tried connecting to the camera with an ONVIF app on my phone through tcp and now i think my camera does support rtsp over tcp but the container does not start without the above environment variable. Instead it throws this error : 
`docker run --rm --privileged -v /dev/bus/usb:/dev/bus/usb -v  path/config:/config:ro -e  RTSP_PASSWORD='pass' -p 5000:5000 blakeblackshear/frigate:edgetpu`

On connect called
Traceback (most recent call last):
  File "detect_objects.py", line 90, in <module>
    main()
  File "detect_objects.py", line 44, in main
    cameras[name] = Camera(name, config, prepped_frame_queue, client, MQTT_TOPIC_PREFIX)
  File "/opt/frigate/frigate/video.py", line 119, in __init__
    self.frame_shape = get_frame_shape(self.rtsp_url)
  File "/opt/frigate/frigate/video.py", line 100, in get_frame_shape
    frame_shape = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'


So i am even more confused now...

**Comment by blakeblackshear** [comment]
When the process first starts, it fetches a single frame to determine the resolution of the video stream. The `NoneType` error you are seeing means that it failed to fetch that first frame. For the high confidence false positives, I would try setting `-e DEBUG="1"`. That will write an image file for each detected person to `/lab/debug/` which may give you an idea of what the process is actually seeing.

**Comment by koncode** [comment]
Just did that it it gives me the below output:

On connect called
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
W third_party/darwinn/driver/package_registry.cc:65] Minimum runtime version required by package (5) is lower than expected (10).
Capture process for back: 31
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
192.168.0.156 - - [14/Apr/2019 16:28:22] "GET /back HTTP/1.1" 200 -
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
...

I don't have a /lab/debug/ dir inside the container though.

**Comment by blakeblackshear** [comment]
Sorry. I forgot that I removed that feature when I implemented Coral support. I am not sure what would be different about your video feed. What camera are you using?

**Comment by koncode** [comment]
I tried with many different cameras and the issue remains. 
Even with the demo object detection from the official site i have the same issue!
![detection_results](https://user-images.githubusercontent.com/10908240/56171942-f0020f00-5fef-11e9-9220-b0d2f4eab621.jpg)
So, at the moment, i don't think there are any problems with your code.
I will close the issue now. Feel free to keep it open if you think it may help someone in the future.
Thanks again.
