### ISSUE TITLE
[Support]:  K8/0.10.0-beta5-amd64 - Fails to start... duplicate column name: objects

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#2434]
### Describe the problem you are having

Container on pristine helm deployment fails with the following - With clean PV

### Version

0.10.0-beta5-amd64 

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
21-12-13 03:53:34] peewee_migrate INFO : Starting migrations
[2021-12-13 03:53:34] peewee DEBUG : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2021-12-13 03:53:34] peewee DEBUG : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
[2021-12-13 03:53:34] peewee DEBUG : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
[2021-12-13 03:53:34] peewee DEBUG : ('BEGIN', None)
Migrate "006_add_motion_active_objects"
[2021-12-13 03:53:34] peewee_migrate INFO : Migrate "006_add_motion_active_objects"
add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)
[2021-12-13 03:53:34] peewee_migrate INFO : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)
[2021-12-13 03:53:34] peewee DEBUG : ('ALTER TABLE "recordings" ADD COLUMN "objects" INTEGER', [])
duplicate column name: objects
[cmd] python3 exited 1
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

Kubernetes - same error should occur in and containerd

**Comment by doug62** [comment]
0.10.0-beta4-amd64  works tho

**Comment by blakeblackshear** [comment]
Strange. It's like the database migration was interrupted somehow. Do you happen to have a backup from before the upgrade?

**Comment by doug62** [comment]
I'm still installing/evaluating, I rebuild it from a k8/helm/script pristine with the hart  persistent.retain: false AND I ensure to delete the data volume on each start so I intentionally don't have a backup - strange that it thought a migration was needed but I do understand how code internally does an up or something like that - LMK if you want more diagnostics, and/or how to trigger more, or if you want me to tray another imae.

**Comment by blakeblackshear** [comment]
I think I know what it might be then.

**Comment by peterloron** [comment]
I'm seeing the same error on beta5, clean docker-compose install.

**Comment by jcastro** [comment]
same error here, downgraded back to beta4 and it works fine

**Comment by blakeblackshear** [comment]
I fixed this and will be pushing a beta6 shortly

**Comment by blakeblackshear** [comment]
This should be resolved now.

**Comment by anandr165** [comment]
@blakeblackshear I'm still seeing this issue on 0.10.0-beta6-amd64nvidia
`mqtt:
  host: 192.168.1.17
  user: 
  password: 

cameras:
  front_camera_frigate:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy 
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: true
      retain_days: 10`

**Comment by anandr165** [comment]
Full error log corresponding to my beta6 issue:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2021-12-19 03:31:22] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:31:22] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:31:22] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:31:22] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:22] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:35] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:31:35] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:31:35] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:31:35] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:35] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:47] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:31:47] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:31:47] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:31:47] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:47] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:53] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:31:53] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:31:53] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:31:53] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:31:53] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:00] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:32:00] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:32:00] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:32:00] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:00] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:07] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:32:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:32:07] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:32:07] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:07] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

Migration failed: 006_add_motion_active_objects

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql

    cursor.execute(sql, params or ())

sqlite3.OperationalError: duplicate column name: objects


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/peewee_migrate/router.py", line 179, in run_one

    migrator.run()

  File "/usr/local/lib/python3.8/dist-packages/peewee_migrate/migrator.py", line 136, in run

    op.run()

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 164, in run

    self._handle_result(method(*self.args, **kwargs))

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 158, in _handle_result

    self._handle_result(item)

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 155, in _handle_result

    result.run()

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 164, in run

    self._handle_result(method(*self.args, **kwargs))

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 153, in _handle_result

    self.execute(result)

  File "/usr/local/lib/python3.8/dist-packages/playhouse/migrate.py", line 149, in execute

    self.migrator.database.execute(node)

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3142, in execute

    return self.execute_sql(sql, params, commit=commit)

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3136, in execute_sql

    self.commit()

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2902, in __exit__

    reraise(new_type, new_type(exc_value, *exc_args), traceback)

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 185, in reraise

    raise value.with_traceback(tb)

  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql

    cursor.execute(sql, params or ())

peewee.OperationalError: duplicate column name: objects

[2021-12-19 03:32:16] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:32:16] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:32:16] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:32:16] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:16] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:28] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:32:28] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:32:28] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:32:28] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:28] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:48] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:32:48] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:32:48] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:32:48] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:32:48] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:33:20] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:33:20] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:33:20] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:33:20] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:33:20] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:34:19] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:34:19] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:34:19] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:34:19] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:34:19] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:35:28] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:35:28] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:35:28] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:35:28] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:35:28] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:36:33] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:36:33] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:36:33] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:36:33] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:36:33] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:37:40] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:37:40] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:37:40] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:37:40] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:37:40] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:38:47] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)

[2021-12-19 03:38:47] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'

Starting migrations

[2021-12-19 03:38:47] peewee_migrate                 INFO    : Starting migrations

Migrate "006_add_motion_active_objects"

[2021-12-19 03:38:47] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"

add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

[2021-12-19 03:38:47] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)

duplicate column name: objects

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

**Comment by srvoets** [comment]
I am experiencing this on the latest nvidia release.  My compose worked previously on an older version of frigate (month behind, but it worked great) had to nuke that ubuntu machine last night, and have other dockers using my gpu passthrough, but cannot get frigate to start:

`| [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-04-27 18:34:33] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate    | Starting migrations
frigate    | [2022-04-27 18:34:33] peewee_migrate                 INFO    : Starting migrations
frigate    | [2022-04-27 18:34:33] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate    | [2022-04-27 18:34:33] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate    | There is nothing to migrate
frigate    | [2022-04-27 18:34:33] peewee_migrate                 INFO    : There is nothing to migrate
voets@ross:~/docker/frigate$
`
