### ISSUE TITLE
[Support]: Upgrade core to core-2021.12.1 shows problem can't reboot HA server

### ISSUE THREAD

**Issue by wagsss** [blakeblackshear/frigate#2443]
### Describe the problem you are having

log shows~

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 21:14:21 (1 occurrences)
Last logged: 21:14:21

Setup failed for conversation: Unable to import component: cannot import name 'HTTP_INTERNAL_SERVER_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### Version

0

### Frigate config file

```yaml
0
```

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 21:14:21 (1 occurrences)
Last logged: 21:14:21

Setup failed for conversation: Unable to import component: cannot import name 'HTTP_INTERNAL_SERVER_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

### FFprobe output from your camera

```shell
0
```

### Frigate stats

```json
0
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

0

**Comment by rhatguy** [comment]
update your frigate integration in HACS if you're installed that way.  There is already a fix in place that returned all of my cams to working once the updated integration was installed.

**Comment by wagsss** [comment]
> update your frigate integration in HACS if you're installed that way. There is already a fix in place that returned all of my cams to working once the updated integration was installed.

I don't have install frigate integration !
After I install frigate integration and restare HA server, the problem still there.

**Comment by wagsss** [comment]
Still not working................

Setup failed for conversation: Unable to import component: cannot import name 'HTTP_INTERNAL_SERVER_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by rhatguy** [comment]
I believe this link is to another report of this same problem.

https://github.com/blakeblackshear/frigate/issues/2430

This issue was fixed in frigate-hass-integration version 2.2.0 6 days ago.  Can you validate if you have the "Frigate" integration installed in home assistant via HACS?

**Comment by wagsss** [comment]
> I believe this link is to another report of this same problem.
> 
> #2430
> 
> This issue was fixed in frigate-hass-integration version 2.2.0 6 days ago. Can you validate if you have the "Frigate" integration installed in home assistant via HACS?

can't add Frigate :  "Failed to connect"

I'm confused,  the core maybe have some bug,  but we need install other integration to fix it?

Anyway, thank you! I will try to add Frigate~

**Comment by wagsss** [comment]
Still have the wrong log.
I can't add frigate-hass-integration shows the "Failed to connect".
I don't understand if I do not need the frigate integrate why should I install it?
Why the core upgrate to core-2021.12.7 still can't fix the problem?
