### ISSUE TITLE
[Support]: Object in a bounding that is touching the edge of the screen is not always recognised as beeing in the zone

### ISSUE THREAD

**Issue by Arquiteto** [blakeblackshear/frigate#3697]
### Describe the problem you are having

I have a camera watching my driveway. I was about to use frigate to (among others) have sort of presence detection for my cars, but it's not reliable for the car that doesn't fit entirely in the view. Below are 2 screenshots, taken just a few secons after each other. On one of them car is detected as beeing in the zone, on the other it's considered out of the zone.

![image](https://user-images.githubusercontent.com/33292677/186027919-8971e9f1-d842-4eb4-9545-41b8b9b4cba8.png)

![image](https://user-images.githubusercontent.com/33292677/186027945-1ac1cfbd-8c46-4942-83dd-135d136524ea.png)

My guess is the problem is caused by the fact, that bounding box is touching the edge of the screen. Can I fix it somehow or is it a bug?

### Version

0.11.0-37325C7

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "front": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 360,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "http://192.168.1.171/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=Sentimenta1",
            "roles": [
              "record",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "http://192.168.1.171/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=Sentimenta1",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i http://192.168.1.171/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=Sentimenta1 -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/front",
          "roles": [
            "record",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i http://192.168.1.171/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=Sentimenta1 -r 7 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "362,0,640,0,640,31,370,27"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 1000,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "front",
      "objects": {
        "filters": {
          "car": {
            "mask": [
              "0,0,162,0,255,0,265,85,0,180"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 4000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.4
          },
          "dog": {
            "mask": null,
            "max_area": 8000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.5
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "car",
          "person",
          "cat",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": [
            "car",
            "person",
            "cat",
            "dog"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "wjazd",
            "wejscie"
          ],
          "retain": {
            "default": 2,
            "mode": "motion",
            "objects": {
              "person": 2
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "podjazd",
          "wejscie",
          "grzybowa",
          "seat",
          "leaf",
          "wjazd"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "grzybowa": {
          "coordinates": "640,47,337,27,302,50,480,75,640,113",
          "filters": {},
          "objects": []
        },
        "leaf": {
          "coordinates": "557,360,564,312,271,315,266,360",
          "filters": {},
          "objects": [
            "car"
          ]
        },
        "podjazd": {
          "coordinates": "0,228,306,88,640,177,640,360,0,360",
          "filters": {
            "dog": {
              "mask": null,
              "max_area": 12000,
              "max_ratio": 24000000,
              "min_area": 0,
              "min_ratio": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 24000000,
              "max_ratio": 24000000,
              "min_area": 1000,
              "min_ratio": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": []
        },
        "seat": {
          "coordinates": "241,297,241,252,95,250,95,296",
          "filters": {},
          "objects": [
            "car"
          ]
        },
        "wejscie": {
          "coordinates": "0,222,0,360,147,360,290,277,452,144,333,100",
          "filters": {
            "dog": {
              "mask": null,
              "max_area": 12000,
              "max_ratio": 24000000,
              "min_area": 0,
              "min_ratio": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 24000000,
              "max_ratio": 24000000,
              "min_area": 1000,
              "min_ratio": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "person",
            "dog",
            "cat"
          ]
        },
        "wjazd": {
          "coordinates": "640,300,640,174,367,98,218,150",
          "filters": {},
          "objects": [
            "car"
          ]
        }
      }
    },
    "salon": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 360,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:Sentimenta1@192.168.1.172:554/h264Preview_01_main",
            "roles": [
              "record",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:Sentimenta1@192.168.1.172:554/h264Preview_01_sub",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i rtsp://frigate:Sentimenta1@192.168.1.172:554/h264Preview_01_main -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/salon-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/salon",
          "roles": [
            "record",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i rtsp://frigate:Sentimenta1@192.168.1.172:554/h264Preview_01_sub -r 7 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "432,0,640,0,640,35,434,33"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 1000,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "salon",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 4000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.4
          },
          "dog": {
            "mask": null,
            "max_area": 8000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.5
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": [
            "person",
            "cat"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 1,
            "mode": "motion",
            "objects": {
              "person": 2
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    },
    "tomek": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 360,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:Sentimenta1@192.168.1.173:554/h264Preview_01_main",
            "roles": [
              "record",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:Sentimenta1@192.168.1.173:554/h264Preview_01_sub",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i rtsp://frigate:Sentimenta1@192.168.1.173:554/h264Preview_01_main -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/tomek-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/tomek",
          "roles": [
            "record",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -i rtsp://frigate:Sentimenta1@192.168.1.173:554/h264Preview_01_sub -r 7 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "432,0,640,0,640,35,434,33"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 1000,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "tomek",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 4000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.4
          },
          "dog": {
            "mask": null,
            "max_area": 8000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.5
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": [
            "person",
            "cat"
          ],
          "post_capture": 5,
          "pre_capture": 60,
          "required_zones": [],
          "retain": {
            "default": 1,
            "mode": "motion",
            "objects": {
              "person": 2
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 7,
    "height": 360,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 640
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": "-f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "core-mosquitto",
    "password": "Sentimenta1",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mosquitto"
  },
  "objects": {
    "filters": {
      "cat": {
        "mask": null,
        "max_area": 4000,
        "max_ratio": 24000000,
        "min_area": 0,
        "min_ratio": 0,
        "min_score": 0.5,
        "threshold": 0.4
      },
      "dog": {
        "mask": null,
        "max_area": 8000,
        "max_ratio": 24000000,
        "min_area": 0,
        "min_ratio": 0,
        "min_score": 0.5,
        "threshold": 0.5
      }
    },
    "mask": "",
    "track": [
      "person"
    ]
  },
  "plus": {
    "enabled": false
  },
  "record": {
    "enabled": true,
    "events": {
      "objects": [
        "person",
        "cat"
      ],
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 1,
        "mode": "motion",
        "objects": {
          "person": 2
        }
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
{"detection_fps":24.63,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.42,"pid":216}},"front":{"camera_fps":7.1,"capture_pid":226,"detection_fps":15.0,"pid":220,"process_fps":7.1,"skipped_fps":0.0},"salon":{"camera_fps":7.5,"capture_pid":228,"detection_fps":7.03,"pid":221,"process_fps":6.2,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":4097.1,"mount_type":"tmpfs","total":4099.7,"used":2.5},"/media/frigate/clips":{"free":6419.1,"mount_type":"ext4","total":117388.1,"used":106158.8},"/media/frigate/recordings":{"free":6419.1,"mount_type":"ext4","total":117388.1,"used":106158.8},"/tmp/cache":{"free":4091.3,"mount_type":"tmpfs","total":4099.7,"used":8.4}},"temperatures":{},"uptime":16,"version":"0.11.0-37325c7"},"tomek":{"camera_fps":7.2,"capture_pid":231,"detection_fps":2.6,"pid":224,"process_fps":7.2,"skipped_fps":0.0}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink RLC-410W

**Comment by NickM-27** [comment]
Can you please list out the zones and their corresponding colors so it is clear which is which? Thanks!

**Comment by Arquiteto** [comment]
Sure,

```
zones:
      grzybowa: # orange
        coordinates: 640,47,337,27,302,50,480,75,640,113
      podjazd: # green
        coordinates: 0,228,306,88,640,177,640,360,0,360
      wejscie: # pink
        coordinates: 0,222,0,360,147,360,290,277,452,144,333,100
      seat: # purple
        coordinates: 241,297,241,252,95,250,95,296
      leaf: # blue
        coordinates: 557,360,564,312,271,315,266,360
      wjazd: # yellow
        coordinates: 640,300,640,174,367,98,218,150
```
The zone I have issue with is called "leaf" and is blue color.

![image](https://user-images.githubusercontent.com/33292677/186085041-acb35547-f716-4e10-8f12-1a5b4ec57be6.png)

**Comment by NickM-27** [comment]
Thank you, does the green zone show 1 or 2 cars detected in this situation?

**Comment by NickM-27** [comment]
Do you have "events" being captured for these cars? If so, if you can get the info from `http://frigate_ip:5000/api/events/` with the correct one would be immensely helpful in seeing what is going on here.

**Comment by Arquiteto** [comment]
> Thank you, does the green zone show 1 or 2 cars detected in this situation?

Green zone shows one car in this situation.

> Do you have "events" being captured for these cars? If so, if you can get the info from `http://frigate_ip:5000/api/events/` with the correct one would be immensely helpful in seeing what is going on here.

I'm gonna try to catch it tomorrow.


For the time being I edited values of the coordinates to extend beyond the picture and it seems it worked. So my guess after analysis is that model recognizes that it sees only a part of a car and estimates bounding box beyond the frame. This way the middle bottom of the bounding box is effectively out of the zone if the zone only extends to the edge of the frame.

**Comment by NickM-27** [comment]
Thanks, I have already reproduced it now and am having a fix in the works. You are correct that the calculated box for the object extends beyond the frame and that is what has caused this issue.

**Comment by NickM-27** [comment]
This has been fixed in 0.11 RC2

**Comment by jmmyerz** [comment]
![image](https://user-images.githubusercontent.com/12993229/189545437-0d8bfd85-12e0-49e4-8e66-a6dd786b91cf.png)

@NickM-27  I'm still having this issue on 0.11 RC2 (0.11.0-c461c9e). The image above should (I believe) count 1 car in the zone based on confidence, but It's counting 0. Occasionally, when the vehicle on the left gets a higher confidence score, it will change to 1. Rarely does it recognize both, but when it does I am able to see the lower portion of the white car's bounding box.

Debug: 
```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "garage_east": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/101",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/102",
            "roles": [
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/103",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": "-c:v copy -c:a aac -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garage_east-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/102 -c:v copy -c:a aac -f flv rtmp://127.0.0.1/live/garage_east",
          "roles": [
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:[redacted]@10.13.2.221:554/Streaming/Channels/103 -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 1
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "1280,0,1280,343,0,387,0,0"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "garage_east",
      "objects": {
        "filters": {
          "bicyle": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "dog",
          "bicyle",
          "motorcycle",
          "car"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "driveway"
          ],
          "retain": {
            "default": 14,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 30,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "driveway": {
          "coordinates": "0,720,1280,720,1280,459,1105,359,0,406",
          "filters": {},
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "pci:0",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-timeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
      "rtmp": "-c:v copy -c:a aac -f flv"
    }
  },
  "live": {
    "height": 720,
    "quality": 1
  },
  "logger": {
    "default": "info",
    "logs": {
      "frigate.app": "debug"
    }
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": {
    "contour_area": 30,
    "delta_alpha": 0.2,
    "frame_alpha": 0.2,
    "frame_height": 50,
    "improve_contrast": false,
    "mask": [
      "0,355,1280,319,1280,0,0,0"
    ],
    "mqtt_off_delay": 30,
    "threshold": 25
  },
  "mqtt": {
[redacted]
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "frigate"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person",
      "cat",
      "dog",
      "bicyle",
      "motorcycle",
      "car"
    ]
  },
  "plus": {
    "enabled": true
  },
  "record": {
    "enabled": true,
    "events": {
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 14,
        "mode": "active_objects",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 2,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 30,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

**Comment by jmmyerz** [comment]
I was able to capture this event data when the white car was counted:
```json
{
  "before": {
    "id": "1662924869.841532-945a8u",
    "camera": "garage_east",
    "frame_time": 1662925743.928876,
    "snapshot_time": 1662924873.926731,
    "label": "car",
    "top_score": 0.75390625,
    "false_positive": false,
    "start_time": 1662924869.841532,
    "end_time": null,
    "score": 0.75390625,
    "box": [
      307,
      295,
      882,
      717
    ],
    "area": 242650,
    "ratio": 1.3625592417061612,
    "region": [
      203,
      0,
      999,
      796
    ],
    "stationary": true,
    "motionless_count": 4351,
    "position_changes": 1,
    "current_zones": [
      "driveway"
    ],
    "entered_zones": [
      "driveway"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "after": {
    "id": "1662924869.841532-945a8u",
    "camera": "garage_east",
    "frame_time": 1662925804.287795,
    "snapshot_time": 1662924873.926731,
    "label": "car",
    "top_score": 0.75390625,
    "false_positive": false,
    "start_time": 1662924869.841532,
    "end_time": null,
    "score": 0.75390625,
    "box": [
      307,
      295,
      882,
      717
    ],
    "area": 242650,
    "ratio": 1.3625592417061612,
    "region": [
      203,
      0,
      999,
      796
    ],
    "stationary": true,
    "motionless_count": 4653,
    "position_changes": 1,
    "current_zones": [
      "driveway"
    ],
    "entered_zones": [
      "driveway"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "type": "update"
}
```

**Comment by NickM-27** [comment]
@jmmyerz The line for the zone is thickened which means it is considering at least one object in the zone.

It seems you're saying the hass sensor is showing 0 which is likely a separate issue.

Also the event data that worked shows the cars bounding box as lower (closer to the edge) so that would say the fix for this particular issue did work.

In any case what you're talking about is unrelated to this issue and I'd recommend making your own.

**Comment by sophof** [comment]
I just updated to 0.11.0 RC2 since I'm running into this issue: I have many events in my timeline and it appears to be because the object (me) is 'flickering' in and out of the zone. However, the issue appears to be still there after the update. I'm watching the debug view and slightly moving will sometimes still trigger the bounding box to be outside the zone. 

Most of the time the bottom of the box will be above the bottom of the zone (which I assume is the fix, but sometimes it will suddenly drop down.

**Comment by NickM-27** [comment]
> I just updated to 0.11.0 RC2 since I'm running into this issue: I have many events in my timeline and it appears to be because the object (me) is 'flickering' in and out of the zone. However, the issue appears to be still there after the update. I'm watching the debug view and slightly moving will sometimes still trigger the bounding box to be outside the zone. 
> 
> 
> 
> Most of the time the bottom of the box will be above the bottom of the zone (which I assume is the fix, but sometimes it will suddenly drop down.

Well, I have fixed another edge case where it still occurred, that will be in RC3. 

However, this won't cause multiple events as an event only stops when the object is no longer visible (stopping has nothing to do with zones).

**Comment by NickM-27** [comment]
closing as this is fixed
