### ISSUE TITLE
Coral USB not detected during boot of PI4 (0.80/Home Assistant) - requires manual restart of Frigate

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#381]
I'm running HASSOS (x64) on PI4 booting from SSD.
Frigate Beta 0.8

Coral config:
```
detectors:
  coral:
    type: edgetpu
    device: usb
```

When I reboot HASSOS, the coral device is not detected:

```
 * Starting nginx nginx
   ...done.
Matplotlib is building the font cache; this may take a moment.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Camera processor started for Voordeur: 37
detector.coral                 INFO    : Starting detection process: 35
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for Voordeur: 39
ffmpeg.Voordeur.clips          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.Voordeur.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5583d2ec10] moov atom not found
/media/frigate/recordings/Voordeur-20201215093539.mp4: Invalid data found when processing input
frigate.record                 INFO    : bad file: Voordeur-20201215093539.mp4
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.
```

Just restarting frigate will solve the problem:
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
detector.coral                 INFO    : Starting detection process: 36
frigate.app                    INFO    : Camera processor started for Voordeur: 39
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
frigate.app                    INFO    : Capture process started for Voordeur: 41
ffmpeg.Voordeur.clips          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.Voordeur.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b10edc10] moov atom not found
/media/frigate/recordings/Voordeur-20201215094501.mp4: Invalid data found when processing input
frigate.record                 INFO    : bad file: Voordeur-20201215094501.mp4
```

Not sure if it is possible to do some retries when a previous run instance was using a coral device

**Comment by mattheys** [comment]
I think I get the same, at least every time I reboot my Rock Pi, frigate comes up in CPU mode and I have to restart the container.

**Comment by blakeblackshear** [comment]
I may just remove the fallback. Once you have a Coral, you don't really want it to fallback to CPU anyway.

**Comment by Ysbrand** [comment]
Not really sure about removing the fallback as a user might go back to cpu detection (lets say the coral device was faulty).

How about:
If there is a detectors section in the config, we force frigate to use the coral device, otherwise we just go for cpu?

**Comment by blakeblackshear** [comment]
Simple enough. I can add a fallback_to_cpu option that defaults to true if you dont have anything defined and defaults to false if you have the edge tpu defined.

**Comment by mattheys** [comment]
Would a configurable timeout work? So if it's set to use an Edge TPU and it isn't detected straight away then keep retrying for x seconds, then fall back to CPU? You could keep the default as 0 seconds so it would still work the same as it does now. That would have a benefit of if there is something wrong with the Edge TPU then at least you will get some detection rather than nothing if you wait forever.

**Comment by lawrence-jeff** [comment]
I had this issue today on a pI4 reboot. Restart detected it

**Comment by S-Przybylski** [comment]
I have the same issue. I use HA to restart the docker container by automation as a workaround - see #450

**Comment by blakeblackshear** [comment]
Should be resolved in RC1

**Comment by Ysbrand** [comment]
Hi,

Unfortunately this is not resolved, Yes, it retries multiple times but it fails to find the coral USB. I'm under the impression that coral is not yet detected by the docker. Restarting frigate (which restarts the docker fixes the problem (without doing anything else).

**Comment by blakeblackshear** [comment]
Hmm. Maybe I can exit the processes and let docker restart the container after a couple retries.

**Comment by Ysbrand** [comment]
Yes, that sounds like a good idea. But in that case please make sure we try only once or twice as you do not want to initiate a forever reboot loop.

**Comment by blakeblackshear** [comment]
If I exit the container, my code loses all state. I won't know if this is the first time or the millionth time. You may be able to set some kind of max restart value in docker itself.

**Comment by Ysbrand** [comment]
When of course a challenge when running the HA add-on.
Are you able to write something in the config yaml, or is that read-only as well?

**Comment by Ysbrand** [comment]
I will do a cold start later today and post the logs

**Comment by blakeblackshear** [comment]
RC4 will now completely exit the container if the detection process stops
