### ISSUE TITLE
[HW Accel Support]: Significant increase in CPU usage between 0.11.1 and 0.12.0-beta3 on RPi4 with hardware decoding

### ISSUE THREAD

**Issue by daernsinstantfortress** [blakeblackshear/frigate#5071]
### Describe the problem you are having

Significant increase in CPU after switching from 0.11.1 to 0.12.0-beta3 on RPi4. Prior to this, CPU usage was around 30-35%, post upgrade around 60-65%. Was successfully using hardware decoding with `-c:v h264_v4l2m2m` but switched to `preset-rpi-64-h264` prior to upgrade as per instructions. Using Coral TPU USB. HA integration updated to 4.0.0 beta 2:

![image](https://user-images.githubusercontent.com/7900720/212350350-1f9979fd-084e-4082-9d18-b40e1e5d4f3b.png)

I am still running older HAOS (8.5) which still supported the previous version of ffmpeg. Is it a requirement to move to the latest (9.4) version in order to regain proper hardware decoding support?

Sample camera report from the system tab:

```
Process | P-ID | FPS | CPU % | Memory %
-- | -- | -- | -- | --
ffmpeg | 296 | 8.1 | 21.9% | 1.4%
Capture | 291 | 8.1 | 9.6% | 2.4%
Detect | 277 | 0 (0 skipped) | 3.0% | 2.6%
```

Similar ffmpeg CPU usage observed on the other identical cameras, with the older cameras reporting lower CPUs (480p rather than 720p.

System tab:
![image](https://user-images.githubusercontent.com/7900720/212349913-158e593d-44f6-49d8-a775-d7e53b0d7a25.png)

### Version

0.12.0-beta3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.94
  port: 1883
  user: <redacted>
  password: <redacted>
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
objects:
    track:
      - person
    filters:
      person:
        max_area: 100000
        max_ratio: 0.7  
cameras:
  driveway:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.12:554/Streaming/Channels/103
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        crop: false
        required_zones:
          - lower_drive 
      motion:
        mask:
          - 407,49,404,0,22,0,22,52
      record:
        events:
          objects:
            - person
            - car
          required_zones:
            - lower_drive    
      mqtt:
        required_zones:
          - lower_drive 
      zones:
        lower_drive:
          coordinates: 1280,720,1280,314,969,267,685,250,326,258,226,340,0,344,0,720
        road:
          coordinates: 1280,0,1280,314,969,267,685,250,326,258,226,340,0,344,0,0
      objects:
        track:
          - person
          - car
        # filters:
        #   car:
        #     min_score: 0.75
        #   person:
        #     min_area: 3000
        #     max_area: 100000
        #     min_score: 0.5
        #     threshold: 0.7      
  back_door:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.14:554/Streaming/Channels/103
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
        required_zones:
          - upper_drive 
      mqtt:
        required_zones:
          - upper_drive         
      motion:
        mask:
          - 407,72,407,32,22,34,27,76
      record:
        events:
          objects:
            - person
            - car
            - dog
          required_zones:
            - upper_drive 
      zones:
        upper_drive:
          coordinates: 1280,720,1280,622,1063,293,965,188,910,425,739,114,559,109,560,0,336,0,136,83,70,106,0,160,0,720
          objects:
            - person
            - car
            - dog
      objects:
          track:
            - person
            - car
            - dog
          filters:
            person:
              mask:
                - 770,120,770,0,992,0,916,394
  patio:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.11:554/Streaming/Channels/103
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 407,49,404,0,22,0,22,52
      objects:
          track:
            - person
            - dog
      zones:
        lower_garden:
          coordinates: 0,720,1280,720,1280,0,0,0

  garage_door:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.15:554/Streaming/Channels/102
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 218,24,220,48,24,49,26,21        
      zones:
        passage:
          coordinates: 0,0,0,480,640,480,640,0          
  back_garden:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.6:554/Streaming/Channels/102
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 22,44,220,40,219,21,23,21
      objects:
          track:
            - person
            - dog
      zones:
        middle_garden:
          coordinates: 0,480,640,480,640,0,0,0
  garage:
      ffmpeg:
        inputs:
          - path: rtsp://<redacted>@192.168.254.16:554/Streaming/Channels/102
            roles:
              -detect
              -rtmp
        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      zones:
        garage_inside:
          coordinates: 0,0,0,480,640,480,640,0
      # motion:
      #   mask:
      #     - 0,25,204,27,209,0,0,0
```

### docker-compose file or Docker CLI command

```yaml
HASS Add-on.
```

### Relevant log output

```shell
Startup log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/prepare-logs.sh
cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun frigate (no readiness notification)
services-up: info: copying legacy longrun go2rtc (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
2023-01-13 14:48:17.759574301  14:48:17.759 INF go2rtc version 0.1-rc.7 linux/arm64
2023-01-13 14:48:17.760684651  14:48:17.760 INF [api] listen addr=:1984
2023-01-13 14:48:17.761120883  14:48:17.760 INF [rtsp] listen addr=:8554
2023-01-13 14:48:17.762112846  14:48:17.761 INF [webrtc] listen addr=:8555
2023-01-13 14:48:17.762548968  14:48:17.762 INF [srtp] listen addr=:8443
2023-01-13 14:48:22.131873800  [2023-01-13 14:48:22] frigate.app                    INFO    : Starting Frigate (0.12.0-cf2466c)
2023-01-13 14:48:22.345989221  [2023-01-13 14:48:22] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-01-13 14:48:22.354494302  [2023-01-13 14:48:22] peewee_migrate                 INFO    : Starting migrations
2023-01-13 14:48:22.372402838  [2023-01-13 14:48:22] peewee_migrate                 INFO    : There is nothing to migrate
2023-01-13 14:48:22.403225780  2023/01/13 14:48:22 [error] 112#112: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate-fa-beta:5000"
2023-01-13 14:48:22.404841379  172.30.32.1 - - [13/Jan/2023:14:48:22 +0000] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
2023-01-13 14:48:22.413522550  [2023-01-13 14:48:22] ws4py                          INFO    : Using epoll
2023-01-13 14:48:22.522084631  [2023-01-13 14:48:22] frigate.app                    INFO    : Output process started: 274
2023-01-13 14:48:22.537984926  [2023-01-13 14:48:22] detector.coral                 INFO    : Starting detection process: 273
2023-01-13 14:48:22.542586895  [2023-01-13 14:48:22] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-01-13 14:48:22.545203772  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for driveway: 277
2023-01-13 14:48:22.561369174  [2023-01-13 14:48:22] ws4py                          INFO    : Using epoll
2023-01-13 14:48:22.563436672  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for back_door: 280
2023-01-13 14:48:22.580889920  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for patio: 282
2023-01-13 14:48:22.611780379  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for garage_door: 284
2023-01-13 14:48:22.659316823  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for back_garden: 287
2023-01-13 14:48:22.695239355  [2023-01-13 14:48:22] frigate.app                    INFO    : Camera processor started for garage: 290
2023-01-13 14:48:22.732994093  [2023-01-13 14:48:22] frigate.app                    INFO    : Capture process started for driveway: 291
2023-01-13 14:48:22.777330783  [2023-01-13 14:48:22] frigate.app                    INFO    : Capture process started for back_door: 295
2023-01-13 14:48:22.834190793  [2023-01-13 14:48:22] frigate.app                    INFO    : Capture process started for patio: 298
2023-01-13 14:48:22.893847122  [2023-01-13 14:48:22] frigate.app                    INFO    : Capture process started for garage_door: 302
2023-01-13 14:48:22.993126172  [2023-01-13 14:48:22] frigate.app                    INFO    : Capture process started for back_garden: 305
2023-01-13 14:48:23.089663978  [2023-01-13 14:48:23] frigate.app                    INFO    : Capture process started for garage: 313
2023-01-13 14:48:24.916798526  [2023-01-13 14:48:24] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-01-13 14:48:30.839611082  172.30.32.1 - - [13/Jan/2023:14:48:30 +0000] "GET /api/stats HTTP/1.1" 200 3242 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
```

### FFprobe output from your camera

```shell
Running ffprobe from the system page just gives the following for all cameras:

[ { "return_code": 1, "stderr": {}, "stdout": {} } ]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2347G2-LU (plus others)

**Comment by NickM-27** [comment]
> Is it a requirement to move to the latest (9.4) version in order to regain proper hardware decoding support?

it's not a requirement but probably recommended.

The issue is with the rpi hwaccel preset which is not limiting FPS which is causing the process to use more CPU. It has already been fixed in https://github.com/blakeblackshear/frigate/pull/5054

**Comment by daernsinstantfortress** [comment]
Thanks for the quick response, Nick, I'll keep an eye out for the next beta. Regarding HAOS, I'll upgrade it once things are stable with Frigate 0.12 so I don't need to rollback again.

**Comment by daernsinstantfortress** [comment]
Just to update on this - I'm now running 0.12.0 beta 5 and am still seeing elevated CPU from 0.11.1. It's better than it was (now stable at around 45-50% utilisation total) but significantly higher than 0.11.1 (30-35%). As expected, frigate system page reports that the majority is still being used by ffmpeg, despite using the `preset-rpi-64-h264` preset.

Happy to open another ticket to investigate if needed.

**Comment by NickM-27** [comment]
We had to move to a different version of ffmpeg so the pi hwaccel can continue to work on the latest kernel, it's possible that this version also uses more CPU and there's not much that can be done for that. I'd recommend updating HA OS as that could potentially help when having the new kernel

**Comment by daernsinstantfortress** [comment]
Thanks Nick - I'm yet to try this but I will report back once I've done so.

**Comment by daernsinstantfortress** [comment]
Looks like CPU utilisation is unchanged after moving to the updated HAOS (9.4) with the newer Pi kernel, so looks like this CPU uplift is something that will have to be lived with for now. It's a shame as, from what I see, it's a significant reduction. Testing on my own system (6 cameras, 5fps, 3 x 720p, 3 x 480p, Coral TPU):

* Removing the hardware acceleration configuration (system page reports "no acceleration configured"):
  * 720p cameras report approx 25% CPU ffmpeg utilisation per camera in the system page
  * RPi overall CPU utilisation is around 45-50%
* Using `preset-rpi-64-h264`:
  * 720p cameras report approx 19-20% CPU ffmpeg utilisation per camera in the system page
  * RPi overall CPU utilisation around 45%

Compared with before, I was seeing 30-35% overall CPU utilisation with the same configuration, it feels that something has got "lost" along the way with the ffmpeg changes made to work around the Pi kernel changes in the summer. For me, it's probably ok - I had enough CPU overhead to support this config - but if someone is working the Pi a bit harder, I suspect they might have a few problems after updating.
