### ISSUE TITLE
[Support]: Object detection at night stopped working in 0.13.0-beta3

### ISSUE THREAD

**Issue by ivitjuk** [blakeblackshear/frigate#8485]
### Describe the problem you are having

I think the new "expected region size estimation" feature regressed object detection in my case. The issue happens at night, on part of the scene that is far away from camera, so objects are small. Motion detection works as expected, and keeps the object within a red box in the debug screen as long as the object is present int the scene. Unfortunately object (person) is not detected at all, even if it stays in the scene for 10s of seconds. No bounding boxes with score and area size appear at all.

I think this is related to the new expected region size computation from historical data because green box around the object is quite large as you can see from the screenshot bellow. Region stays that large as long as the object is in the scene.

Detection under these conditions worked well for months on Frigate 12.

![Screenshot_20231105_210914_com android chrome](https://github.com/blakeblackshear/frigate/assets/875244/41939290-6a39-4113-b69d-4cdd7dc9b5bf)

### Version

0.13.0-beta3

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mosquitto

ui:
  live_mode: webrtc

birdseye:
  enabled: True
  mode: continuous

record:
  enabled: True
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 5
      mode: all

snapshots:
  enabled: True
  clean_copy: False
  crop: False
  retain:
    default: 10

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    street:
      - rtsp://###:###@192.168.1.60:554/Streaming/Channels/101
      - "ffmpeg:street#audio=opus"
    entrance:
      - rtsp://###:###@192.168.1.62:554/Streaming/Channels/101
      - "ffmpeg:entrance#audio=opus"
    terace:
      - rtsp://###:###@192.168.1.61:554/Streaming/Channels/101
      - "ffmpeg:terace#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.10:8555
      - ###:8555

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  street:
    ui:
      order: 0
    mqtt:
      crop: False
      height: 540
      quality: 85
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street
          roles:
            - detect
            - record
    motion:
      improve_contrast: false # HA controlled.
      threshold: 25 # HA controlled d:25/n:20.
      mask:
        - 153,720,1080,720,447,242,442,166,512,132,648,207,716,173,986,222,1280,308,1280,0,0,0,0,294,358,173,419,236,0,402,0,529,327,377,252,637,152,676
    objects:
      track:
        - person
        - car
    record:
      events:
        required_zones:
          - frontyard
          - stairs
          - parking
    snapshots:
      required_zones:
        - frontyard
        - stairs
        - parking
    zones:
      frontyard:
        coordinates: 0,581,367,478,496,720,291,720,220,622,172,720,0,720
        objects:
          - person
      stairs:
        coordinates: 0,386,436,228,440,331,0,482
        objects:
          - person
        filters:
          person:
            max_area: 11000 # Avoid bush.
      parking:
        coordinates: 1061,720,1280,720,1280,445,680,226,434,169,438,244
        objects:
          - car
          - person
  entrance:
    ui:
      order: 1
    mqtt:
      crop: False
      height: 540
      quality: 85
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance
          roles:
            - detect
            - record
    motion:
      improve_contrast: false # HA controlled.
      threshold: 30 # Less sensitive to changes (fixed).
      contour_area: 200 # Less sensitive to small changes.
      mask:
        - 952,98,1280,118,1280,0,698,0,684,285
        - 0,673,370,670,342,500,694,441,698,328,1108,464,1003,720,488,720,0,720
  terace:
    ui:
      order: 2
    mqtt:
      crop: False
      height: 540
      quality: 85
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terace
          roles:
            - detect
            - record
    objects:
      track:
        - person
      filters:
        person:
          max_ratio: 0.65 # Avoid false positives for short objects.
    motion:
      improve_contrast: false # HA controlled.
      threshold: 30 # HA controlled d:30/n:20.
      contour_area: 200 # Less sensitive to small changes.
      mask:
        - 1280,296,1280,0,871,0,856,214
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

EzViz CS-C6N

**Comment by NickM-27** [comment]
This was already fixed in beta 4, it was an issue when there was no historical data in that part of the image

**Comment by ivitjuk** [comment]
I've just pulled ghcr.io/blakeblackshear/frigate:0.13.0-beta4 and the issue is still present. Do I need to manually clear the regions database?

**Comment by NickM-27** [comment]
I would start by accessing `http://frigate_ip:5000/api/<camera_name>/grid.jpg` and show that here, that will give info on what the grid is.

**Comment by ivitjuk** [comment]
Here it is:

![grid](https://github.com/blakeblackshear/frigate/assets/875244/adb6d78e-1afd-4053-8b7d-b6ee704e9e86)

**Comment by NickM-27** [comment]
ah okay I see the issue, I assumed a minimum region size of 320 while creating the grid but openvino has a min region size of 300x300

**Comment by NickM-27** [comment]
Once this merges you will need to clear out the regions DB

**Comment by ivitjuk** [comment]
Thanks, much appreciated!
